title: How to start with using TomTom Maps SDK for Android
tagline: TomTom Maps SDK for Android for Beginners

description:
  to start using TomTom Maps SDK for Android

template:
  name: lab-tomtom-maps-sdk-android
  repo: maps-sdk-for-android-template

before:
  - type: createIssue
    title: Introduuction
    body: 1_introduction.md
  - type: createIssue
    title: Prepare working environment
    body: 2_prepare_working_environment.md
  - type: createIssue
    title: Install dependencies
    body: 3_install_dependencies.md

steps:
  - title: Introduction - Step 1
    description: Get familiar with the course and learn how TomTom GitHub Learning Labs work.
    event: issues
    link: '{{ repoUrl }}/issues/1'
    actions:
    - type: respond
      with: bot_autoresponse.md
      issue: 1

  - title: Pre-requisites - Step 2
    description: To develop your own application with Maps SDK, you need to make sure that the pre-requisites are in place and that you have added Maps SDK  as a dependency into your project. Follow the steps below and then you are ready to code!
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
    - type: respond
      with: 2_init.md
      issue: 1
    - type: respond
      with: bot_autoresponse.md
      issue: 2

  - title: Install dependencies - Step 3
    description: Install all required dependencies
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
    - type: respond
      with: 3_init.md
      issue: 2
    - type: respond
      with: bot_autoresponse.md
      issue: 3
  #
  # - title: Implement ABC
  #   description: Implement description
  #   event: issues.closed
  #   link: '{{ repoUrl }}/issues/2'
  #   actions:
  #   - type: respond
  #     with: 2_install_dependencies_response.md
  #     title: Well done
