title: How to start with using Maps SDK for Android
tagline: android maps sdk
description: Start using TomTom Maps SDK for Android

template:
  name: lab-tomtom-maps-sdk-android
  repo: maps-sdk-for-android-template

before:
- type: createIssue
  title: Prepare working environment
  body: 1_prepare_working_environment.md

steps:
- title: Prepare working environment
  description: Before your start you need to prepare your working environment
  event: issues
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: closeIssue
    issue: 1
  - type: respond
    with: 1_prepare_working_environment_response.md
    issue: 1
  # - type: createIssue
  #   title: Install dependencies
  #   body: 2_install_dependencies.md

# - title: Install dependencies
#   description: Install all required dependencies
#   event: issues
#   link: '{{ repoUrl }}/issues/2'
#   actions:
#   - type: closeIssue
#     issue: 2
#   - type: respond
#     with: 2_install_dependencies_response.md
#     title: Well done
